### ISSUE TITLE
注意该文档中有隐藏的页眉页脚，每个文件都有！！！

### ISSUE THREAD

**Issue by xubeiyan** [cuizhenjie/software-engineering-document#8]
本来把，大家都知道软件工程的文档必要时候抄个格式都是正常的。但是仓库owner的行为，简直是败坏开源精神！因为他竟然在文档里埋**炸弹**。

让我们来看看他的行为：

* 埋藏带有法律声明的页眉页脚

任意打开一个文档文件，这里选择了`01 计划阶段\00 可行性分析\可行性分析 - 模板.docx`，一般这种文档的页眉页脚都是有内容的：

![header](https://user-images.githubusercontent.com/4469398/192426975-2edfa697-05b3-42ec-95a6-6c1e595f9342.png)
![footer](https://user-images.githubusercontent.com/4469398/192427048-45f17636-126b-4cec-8dff-5b415a01bc4c.png)

只需修改一下即可。但是，其实你并没有删干净其中的页眉页脚

当我们删除页眉页脚时，页面如下：

![clear header](https://user-images.githubusercontent.com/4469398/192430705-c94dde51-58a9-401e-867e-04025fedbdad.png)
![clear footer](https://user-images.githubusercontent.com/4469398/192430716-bff4cb9b-3d14-430d-815e-b5e8329055d5.png)

一般到这里就结束了，我也是这么想的，但我鬼使神差用了下MSWord的语法错误检查器，竟然看到了这样的字样。

![bomb](https://user-images.githubusercontent.com/4469398/192431419-772c2fad-0ae2-489f-bd2c-d0df04b43d51.png)

大概就知道了，这个文档本属于“北京中盈安信技术服务有限公司”的内容，要看到这个内容也比较简单。选择页眉页脚，勾上“首页不同”和“奇偶页不同”，就可以看到这个罪魁祸首了。
![hidden header](https://user-images.githubusercontent.com/4469398/192432181-c3381f1c-8a4a-47fd-a9e2-9950dda1cc07.png)
![hidden footer](https://user-images.githubusercontent.com/4469398/192432209-731ab3f9-2c10-4217-9370-ad952aeb9d38.png)

如果你不幸用了这个模板，然后没有移除这个“恶意”的法律声明，那承担的法律风险**后果自负**。

**Comment by xubeiyan** [comment]
这个仓库的License是MIT License，他并不是完全强制开源的License，它允许Commercial use和Modification，所有如果“北京中盈安信技术服务有限公司”要走法律程序起诉使用了他们的模板的人（就是使用了这个仓库内容的你）也是可以的。

**Comment by cuizhenjie** [comment]
请按照开源协议按需借鉴使用，非建议全部copy商业应用。

**Comment by xubeiyan** [comment]
一年多了，再来看，页脚版权信息还是有。建议不要做开源了，害人啊
